config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :guides
  
  resources :spreadsheets do
    collection do
      post :import
    end
  end
  
  resources :sessions
  
  get "admin" => "sessions#new", as: :admin
  

  

end

app/models/guide.rb
class Guide < ActiveRecord::Base
  extend FriendlyId
  include Validation
  friendly_id :use_for_slug, use: [:slugged, :finders]
  before_update :update_slug
  
  [:state, :name, :payer].each { |col| validates col, presence: true}
  
  def use_for_slug
    existing_guide = Guide.where(name: self.name, state: self.state, payer: self.payer)
    existing_guide.present? ? "#{name} for #{payer} in #{state} #{existing_guide.count}" : "#{name} for #{payer} in #{state}"
  end
  
  def minus_self
    Guide.where.not(id: id)
  end
  
  def update_slug
    if (state_changed? || name_changed? || payer_changed?)
      existing_guide = self.minus_self.where('slug = ?', self.slug)
      if existing_guide.present?
        update_column(:slug, "#{ApplicationController.helpers.to_slug(name, "for", payer, "in", state, (existing_guide.count + 1))}")
      else
        update_column(:slug, "#{ApplicationController.helpers.to_slug(name, "for", payer, "in", state)}")
      end
    end
  end
  
  def self.make_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each { |guide|  csv << guide.attributes.values_at(*column_names) }
    end
  end
  
  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path, csv_options: {encoding: "iso-8859-1:utf-8"})
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Spreadsheet.open(file.path, extension: :xlsx)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end
  
  def self.import(file, state)
    spreadsheet = open_spreadsheet(file)
    spreadsheet.sheets.each_with_index do |sheet_name, i|
      sheet = spreadsheet.sheet(sheet_name)
      next if sheet.last_row.nil?
      header = sheet.column(1).collect { |column| column.gsub(" ", "_").downcase unless column.nil?}
      ((sheet.first_column + 1)..sheet.last_column).each do |i|
        model_hash = Hash[[header, sheet.column(i)].transpose].delete_if { |k, v| k.nil? }.except("coverage","published_policies_section", "pa_section", "other_notes_section", "coding", "formulary", "reimbursement", "relationship_to_other_payers" )
        model_hash["products_covered"].split(", ").each do |product_name|
          without_products_hash = model_hash.except("products_covered").merge(state: state, name: product_name)
          object = Guide.where(state: state, name: product_name, payer: model_hash["payer"])
          if object.present? 
             object.first.update_attributes(without_products_hash)
             guide = object.first
          else
             guide = Guide.create!(without_products_hash.merge(id: Guide.last.try(:id).to_i + 1))
          end
           guide.update_booleans(model_hash)
        end
      end
    end
  end
  
  def update_booleans(hash={})
    update_attributes(
      published_policies: hash["published_policies"].to_s.downcase == "yes" ? true : (hash["published_policies"].to_s.downcase == "no" ? false : nil),
      state_mandate_apply: hash["state_mandate_apply"].to_s.downcase == "yes" ? true : (hash["state_mandate_apply"].to_s.downcase == "no" ? false : nil),
      major_medical_benefit: hash["major_medical_benefit"].to_s.downcase == "yes" ? true : (hash["major_medical_benefit"].to_s.downcase == "no" ? false : nil),
      rx_benefit: hash["rx_benefit"].to_s.downcase == "yes" ? true : (hash["rx_benefit"].to_s.downcase == "no" ? false : nil),
      pa_required: hash["pa_required"].to_s.downcase == "yes" ? true : (hash["pa_required"].to_s.downcase == "no" ? false : nil),
      pa_form_required: hash["pa_form_required"].to_s.downcase == "yes" ? true : (hash["pa_form_required"].to_s.downcase == "no" ? false : nil),
      bo_modifier: hash["bo_modifier"].to_s.downcase == "yes" ? true : (hash["bo_modifier"].to_s.downcase == "no" ? false : nil),
      is_s9433: hash["is_s9433"].to_s.downcase == "yes" ? true : (hash["is_s9433"].to_s.downcase == "no" ? false : nil),
      formulary_exception_allowed: hash["formulary_exception_allowed"].to_s.downcase == "yes" ? true : (hash["formulary_exception_allowed"].to_s.downcase == "no" ? false : nil),
      formulary_form_required: hash["formulary_form_required"].to_s.downcase == "yes" ? true : (hash["formulary_form_required"].to_s.downcase == "no" ? false : nil),
      formulary_documentation_required: hash["formulary_documentation_required"].to_s.downcase == "yes" ? true : (hash["formulary_documentation_required"].to_s.downcase == "no" ? false : nil),
      reimbursement_fee_schedule: hash["reimbursement_fee_schedule"].to_s.downcase == "yes" ? true : (hash["reimbursement_fee_schedule"].to_s.downcase == "no" ? false : nil)
    )
  end  
  
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :is_admin, except: %w|index show|
  before_action :find_object, only: %w|show edit|
  
  
  def index
    # search
    @states = params[:state].present? ? Guide.where(state: params[:state]) : Guide.all
    @payers = params[:payer].present? ? Guide.where(payer: params[:payer]) : Guide.all
    @names =  params[:name].present? ? Guide.where(name: params[:name]) : Guide.all
    @guide_ids = @states.pluck(:id) & @payers.pluck(:id) & @names.pluck(:id)
    @guides = Guide.where(id: @guide_ids)
    
    if @guides.present?
      # pagination
      @per_page = 5
      @page = params["page"].to_i
      @page_count = (@guides.count / @per_page) + 1
      @paginated_guides = @guides.limit(@per_page).offset(@per_page * [@page - 1, 0].max)
    end
    
    @guide = @guides.last
    respond_to do |format|
      format.html
      format.csv { send_data @guides.make_csv(params) }
      format.xls  #{ send_data @guides.make_csv(col_sep: "\t") }
    end
  end
  
  def new
    @guide = Guide.new
  end
  
  def create
    @guide = Guide.new(guide_params.merge(id: Guide.last.try(:id).to_i + 1))
    if @guide.save
      redirect_to @guide
    else
      render 'new'
    end
  end
    
  def show;end

  def edit;end
  
  def update
    @guide = Guide.friendly.find(params[:id])
    if @guide.update_attributes(guide_params)
      redirect_to @guide 
    else
      render 'edit'
    end
  end
  
  def destroy
    @guide = Guide.find(params[:id])
    @guide.destroy
    redirect_to guides_path
  end
  
  protected
  
  def guide_params
    params.require(:guide).permit(:state, :name, :payer, :contact, :phone_number, :fax_number, :published_policies, :policy_name, :policy_number, :policy_link, :product_codes_covered, :approved_diagnoses, :approved_diagnoses_codes, :age_limitations, :other_limitations, :state_mandate_apply, :major_medical_benefit, :rx_benefit, :pa_required, :pa_form_required, :pa_link, :pa_process, :coverage_notes, :accepted_billing_codes, :bo_modifier, :is_s9433, :coding_link, :nutricia_formulary_products, :open_or_closed_formulary, :formulary_exception_allowed, :formulary_form_required, :formulary_link, :formulary_documentation_required, :formulary_process, :reimbursement_fee_schedule, :reimbursement_link, :product_reimbursement_rate, :reimbursement_specific, :reimbursement_methodology, :reimbursement_fees, :relationship_to_wic, :relationship_to_state_medicaid, :relationship_to_other_programs, :other_notes)
  end
  
  def find_object
     @guide = Guide.friendly.find(params[:id])
  end
  
end


   

app/views/guides/_multiple_results.html.erb
<body class="">
  <!-- main header -->
  <div id="page_content">
    <div id="page_content_inner">
      
       <%= render 'guides/search' %>
		 
        
        <!-- output table and search results -->
        <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-container uk-width-large-8-10 uk-width-small-10-10 uk-container-center">
          <div class="md-card">
            <div class="md-card-content">
              <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-1-1">
                  <div class="uk-overflow-container">
                    <table class="uk-table uk-table-hover uk-table-responsive">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Product Name</th>
                          <th>Payer State</th>
                          <th>Payer Name</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @paginated_guides.each_with_index do |guide, i| %>
                          <tr>
                            <td><span class="heading_c"><%= i + 1 %></span></td>
                            <td class="uk-text-large uk-text-nowrap">
                              <span class="heading_c"><a href="<%= "guides/#{guide.slug}" %>"><%= guide.name %></a></span>
                            </td>
                            <td class="uk-text-nowrap">
                              <span class="heading_c"><%= guide.state %></span>
                            </td>
                            <td>
                              <span class="heading_c"><%= guide.payer %></span>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                  <%= render 'guides/pagination' %>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
        <!-- end output table and search results -->
		

      
    </div>
  </div>

app/views/guides/_no_results.html.erb
<body class="">
  <!-- main header -->
  <div id="page_content">
    <div id="page_content_inner">
      
      <%= render 'guides/search' %>
       
      <br/>
      <br/>

      <h1 class="uk-text-center">
       	No Results.
      </h1>
      <h3 class="uk-text-center">
     		<span class="sub-heading uk-text-muted">
    			Please try another search using the search form above.
		   	<span>
    	</h3>

      <div>
    </div>
  </div>

app/views/guides/_one_result.html.erb
<%= render 'guides/show' %>

app/views/guides/_pagination.html.erb
<% if @guides.count > @per_page %>
<ul class="uk-pagination uk-margin-medium-top uk-margin-medium-bottom">
   
  <li class="<%= @page == 1 ? "uk-disabled" : "" %>">
    <%= link_to params.merge(:page => 1) do %> 
      <span>
        <i class="material-icons uk-bold md-24">&#xE314;</i>
      </span>
    <% end %>
  </li>
  
  <% if (@page > 3)  %>
  
  <li class=""><span><%= link_to 1, params.merge(:page => 1) %></span></li>
  
  <% end %>
  <% if ((@page - 1) > 2) && (@page != 4) %>
  <li><span>&hellip;</span></li>
  <% end %>
  
  
  
  <% (([1, (@page == 5 ? 4 : (@page == @page_count ? (@page_count - 3) : @page - 2))].max)..@page_count).take(5).to_a.each do |i| %>
    <li class="<%= (@page == i || (@page.zero? && i == 1)) ? "uk-active" : "" %>">
      <span>
      <% if (i >= (@page - 2)) || ((@page_count - i) <= 4) %>
      <%= link_to i, params.merge(:page => i) %>
      <% end %>
     
      </span>
    </li>
  <% end %>
  
  
  <% if (@page_count - @page) > 3 %>
  <li><span>&hellip;</span></li>
  <li class="<%= @page == @page_count ? "uk-active" : "" %>">
    <span>
      <%= link_to @page_count, params.merge(:page => @page_count) %>
    </span>
  </li>
  
  <% end %>
   
  <li class="<%= @page == @page_count ? "uk-disabled" : "" %>">
    <%= link_to params.merge(:page => @page_count) do %>
    <i class="material-icons uk-bold md-24">&#xE315;</i>
    <% end %>
  </li>
  
</ul>
<% end %>

app/views/guides/_search.html.erb
  <div class="uk-grid" data-uk-grid-margin>
    <div class="uk-container uk-width-large-8-10 uk-width-small-10-10 uk-container-center">
      <%= render 'shared/header'%>

      <hr/>
     
      <div class="text-right uk-clearfix">

        <%= link_to guides_path(format: "xls") do %>
          <span class="md-btn uk-float-left uk-margin-top uk-margin-right">Download Excel</span>
        <% end %>
        
        <% if current_user %>
          <% if current_user.admin? %>
            <%= link_to spreadsheets_path, class: "md-btn uk-float-left uk-margin-top" do %>
              Upload Reimbursement Data
              <i class="material-icons uk-margin-small-left">&#xE89D;</i>
            <% end %>
        <% end %>
        <% end %>

      </div>

      <br/>
      <!-- beginning of form -->
      <%= form_tag guides_path, method: :get do %>

      <div class="md-card">
        <div class="md-card-content">
          
          <!-- search field -->
          <div class="uk-grid" data-uk-grid-margin="">

            <!-- payer state -->
            <div class="uk-width-medium-2-10">
              <%= select_tag :state, options_for_select(states, (params[:state] if params[:state].present?)), {class: "data-md-selectize", prompt: "Select State"} %>
            </div>
           <!-- end payer state -->

            <!-- payer Name -->
            <div class="uk-width-medium-2-10">
              <%= select_tag :payer, options_for_select(payer_names, (params[:payer] if params[:payer].present?)), {class: "data-md-selectize", prompt: "Select Payer"} %>
            </div>
            <!-- end payer Name -->

            <!-- Products -->
            <div class="uk-width-medium-3-10">
             <%= select_tag :name, options_for_select(products, (params[:name] if params[:name].present?)), {class: "data-md-selectize", prompt: "Select Nutricia Product"} %>
            </div>
            <!-- end Products -->

            <!-- Submit Button -->
            <div class="uk-width-medium-3-10 uk-text-center">
              <%= submit_tag "Search", class: "md-btn md-btn-block md-btn-primary uk-margin-small-top"%>
            </div>
            <!-- Submit Button -->

          </div>
          <!-- end search field -->

        </div>
      </div>
    </div>
  </div>
<% end %>
<!-- end of form -->

app/views/guides/edit.html.erb
<div class="uk-grid" data-uk-grid-margin>
  <div class="uk-container uk-width-large-8-10 uk-width-small-10-10 uk-container-center">
    
    <div class="uk-grid" data-uk-grid-margin="">
      <div class="uk-width-medium-2-10">
        <%= link_to root_path do %>
          <%= image_tag("http://images.usa-4u.de/Bilder/Shop_Fotos/Nutricia/header/Nutricia_logo.jpg", class: "uk-thumbnail", style: "min-width: 200px; min-height: 85px;")%>
        <% end %>
      </div>
      <div class="uk-width-medium-8-10">
        <h4 class="text-muted uk-margin-small-top uk-margin-bottom-remove">Nutricia</h4> 
        <h1 class="uk-text-muted uk-margin-remove">
          Payor Wizard
        </h1>
      </div>
    </div>

    <hr/>
  </div>
  </div>
  <div class="uk-grid" data-uk-grid-margin>
    <div class="uk-width-5-5 uk-container-center">
    	<%= render 'form' %>
    </div>
  </div>
</div>

app/views/guides/index.html 2.erb
<% if @guide.nil? %>

No records found.

<% else %>

<div class="uk-grid" data-uk-grid-margin>
  <div class="uk-container uk-width-large-8-10 uk-width-small-10-10 uk-container-center">
    <div class="md-card">
      <div class="md-card-content">
        <h5 class="clearfix uk-text-center uk-margin-small-top">
          	Reimbursement Information
        </h5>
        <h2 class="uk-text-center uk-margin-small-top">
        	<span class="uk-text-primary"><%= @guide.name %></span> in 
        	<span class="uk-text-primary"><%= @guide.state %></span> for
        	 <span class="uk-text-primary"><%= @guide.payer %></span> 
        </h3>
      </div>
      <hr class="uk-margin-remove"/>
      <div class="md-card-content uk-margin-remove-top">
				<div class="uk-grid uk-grid-divider" data-uk-grid-margin>
	      	<div class="uk-width-large-1-2 uk-width-medium-1-2 ">
	          <ul class="md-list md-list-addon">
	          	<li>
	              <div class="md-list-addon-element">
	                <i class="md-list-addon-icon material-icons uk-text-primary">&#xE85E;</i>
	              </div>
	              <div class="md-list-content">
	                <h3 class="uk-margin-remove"><%= @guide.contact %></h3>
	                <span class="uk-text-small uk-text-muted">Contact</span>
	              </div>
	            </li>
	            <li>
	              <div class="md-list-addon-element">
	                  <i class="md-list-addon-icon material-icons uk-text-primary">&#xE157;</i>
	              </div>
	              <div class="md-list-content">
	                  <h3 class="uk-margin-remove"><%#= link_to @guide.current_link, @guide.current_link %></h3>
	                  <span class="uk-text-small uk-text-muted">Insurance Website</span>
	              </div>
	            </li>
	            <li>
	              <div class="md-list-addon-element">
	                <i class="md-list-addon-icon material-icons uk-text-primary">&#xE02F;</i>
	              </div>
	              <div class="md-list-content">
	                <h3 class="uk-margin-remove"><%#= @guide.formulary? ? "Yes" : "No" %></h3>
	                <span class="uk-text-small uk-text-muted">Formulary?</span>
	              </div>
	            </li>
	            <li>
	              <div class="md-list-addon-element">
	                <i class="md-list-addon-icon material-icons uk-text-primary">&#xE878;</i>
	              </div>
	              <div class="md-list-content">
	                <h3 class="uk-margin-remove"><%#= "#{@guide.formulary_review_date.strftime("%b")} #{@guide.formulary_review_date.day}, #{@guide.formulary_review_date.year}" %></h3>
	                <span class="uk-text-small uk-text-muted">Formulary Review Date</span>
	              </div>
	            </li>
	            <li>
	              <div class="md-list-addon-element">
	                <i class="md-list-addon-icon material-icons uk-text-primary">&#xE24B;</i>
	              </div>
	              <div class="md-list-content">
	                <h3 class="uk-margin-remove"><%= @guide.reimbursement_methodology %></h3>
	                <span class="uk-text-small uk-text-muted">Reimbursement Methodology</span>
	              </div>
	            </li>
	            <li>
	              <div class="md-list-addon-element">
	                <i class="md-list-addon-icon material-icons uk-text-primary">&#xE0B0;</i>
	              </div>
	              <div class="md-list-content">
	                <h3 class="uk-margin-remove"><%= @guide.phone_number.gsub(" ", ".") %></h3>
	                <span class="uk-text-small uk-text-muted">Phone Number</span>
	              </div>
	            </li>
	            <li>
	              <div class="md-list-addon-element">
	                <i class="md-list-addon-icon material-icons uk-text-primary">&#xE8C5;</i>
	              </div>
	              <div class="md-list-content">
	                <h3 class="uk-margin-remove"><%= @guide.fax_number.gsub(" ", ".") %></h3>
	                <span class="uk-text-small uk-text-muted">Fax Number</span>
	              </div>
	            </li>
	            <li>
	              <div class="md-list-addon-element">
	                  <i class="md-list-addon-icon material-icons uk-text-primary">&#xE873;</i>
	              </div>
	              <div class="md-list-content">
                      <% if false %>
					  <% if @guide.payer_name == "WIC" %>
	                  <h3 class="uk-margin-remove"><%= link_to "Texas WIC Medical Request Form", "/TXWICMedicalRequestforFormula.pdf" %></h3>
					  <% else %>
					  
					  <h3 class="uk-margin-remove"><%= link_to "Texas Medicaid - Medical Policy", "http://www.tmhp.com/News_Items/2010/08-06-10%20Benefit%20Criteria%20Nutritional%20%28Enteral%29%20Products%20Supplies%20Equipment%20Change%20for%20Texas%20Medicaid%20HHS.pdf" %></h3>
					  
					  <h3 class="uk-margin-remove"><%= link_to "Texas Standard Prior Authorization Form", "http://www.tdi.texas.gov/forms/lhlifehealth/nofr001.pdf"  %></h3>
					  
					  <% end %>
                      <% end %>
	                  <span class="uk-text-small uk-text-muted">Forms</span>
	              </div>
	            </li>
	          </ul>
	          <!-- <b>Link Notes:</b> <%#= @guide.link_notes %><br><br> -->

						<!-- <b>Medicaid FFS:</b> <%#= @guide.medicaid_ffs %><br><br> -->

						<!-- <b>Managed Care Medicaid:</b> <%#= @guide.managed_care_medicaid %><br><br> -->

						<!-- <b>Managed Care Medicaid:</b> <%#= @guide.medical_food_policy %><br><br> -->

	      	</div>
					<div class="uk-width-large-1-2 uk-width-medium-1-2 ">

						<div class="uk-grid" data-uk-grid-margin>
							<div class="uk-width-large-1-1">
								<h2 class="uk-text-center uk-margin-bottom-remove uk-margin-small-top">Payer Segment Breakdown (%)</h2>
	      				<%# chart_object = {"Private Commercial" =>@guide.private_commercial, "Medicaid"=>@guide.medicaid, "Uninsured"=> @guide.uninsured, "Medicare/Other Public" =>@guide.medicare_other_public}  %>
								<%#= pie_chart chart_object, colors: ["#1976D2","#D32F2F", "#FF9800", "#388E3C"], library: {legend: {position: "none"}} %>
							</div>
							<div class="uk-width-large-3-4 uk-container-center uk-margin-small-top">

								<div class="uk-grid uk-margin-remove">
	      					<div class="uk-width-large-1-2">
			      				<font style="color:#1976D2" size="5">&#9679;</font>
										<font style="color:black" size="3">Private Commercial</font><br/>
									</div>
									<div class="uk-width-large-1-2">
										<font style="color:#D32F2F" size="5">&#9679;</font>
										<font style="color:black" size="3">Medicaid</font>
									</div>
								</div>

								<div class="uk-grid uk-margin-remove">
	      					<div class="uk-width-large-1-2">
	      						<font style="color:#FF9800" size="5">&#9679;</font>
										<font style="color:black" size="3">Uninsured</font>
									</div>
									<div class="uk-width-large-1-2">
										<font style="color:#388E3C" size="5">&#9679;</font>
										<font style="color:black" size="3">Medicare/Other Public</font>
									</div>
								</div>

							</div>
						</div>

					</div>
	      </div>
	    </div>
  	</div>
	</div>
</div>

<% end %>

app/views/guides/index.html.erb
<% if @guides.count == 0  %>

<%= render 'guides/no_results'%>

<% elsif @guides.count == 1 %>

<%= render 'guides/one_result'%>

<% else %>

<%= render 'guides/multiple_results' %>

<% end %>

app/views/guides/index.xls.erb
<% @guides.pluck(:payer).uniq.each do |payer| %>
  <br>
  <h2><%= payer %></h2>

  <table border="1" border-color="#0000ff">
      <tr bgcolor="#99ddff">
        
          <th>Name</th>
          <th>State</th>
          <th>Payer</th>
          <th>Contact</th>
          <th>Phone Number</th>
          <th>Fax Number</th>
          <th>Published Policies</th>
          <th>Policy Name</th>
          <th>Policy Link</th>
          <th>Product Codes Covered</th>
          <th>Approved Diagnoses</th>
          <th>Approved Diagnoses Codes</th>
          <th>Age Limitations</th>
          <th>Other Limitations</th>
          <th>State Mandate Apply</th>
          <th>Major Medical Benefit</th>
          <th>RX Benefit</th>
          <th>PA Required</th>
          <th>PA Form Required</th>
          <th>PA Link</th>
          <th>PA Process</th>
          <th>Coverage Notes</th>
          <th>Accepted billing codes</th>
          <th>BO modifier</th>
          <th>Is S9433</th>
          <th>Coding Link</th>
          <th>Nutricia Formulary Products</th>
          <th>Open or closed formulary</th>
          <th>Formulary exception allowed</th>
          <th>Formulary Form Required</th>
          <th>Formulary Link</th>
          <th>Formulary Documentation Required</th>
          <th>Formulary Process</th>
          <th>Reimbursement Fee Schedule</th>
          <th>Reimbursement Link</th>
          <th>Product Reimbursement Rate</th>
          <th>Reimbursement Methodology</th>
          <th>Reimbursement Fees</th>
          <th>Other Notes</th>
          <th>Relationship to WIC</th>
          <th>Relationship to State Medicaid</th>     
          <th>Relationship to Other Programs</th>                 
      </tr>
      <% Guide.where(payer: payer).each do |guide| %>
      <tr>
       
          <td><%= guide.name %></td>
          <td><%= guide.state %></td>
          <td><%= guide.payer %></td>
          <td><%= guide.contact %></td>
          <td><%= guide.phone_number %></td>
          <td><%= guide.fax_number %></td>
          <td><%= guide.published_policies? ? "Yes" : (guide.published_policies == false ? "No" : "")  %></td>
          <td><%= guide.policy_name %></td>
          <td><%= guide.policy_link %></td>
          <td><%= guide.product_codes_covered %></td>
          <td><%= guide.approved_diagnoses %></td>
          <td><%= guide.approved_diagnoses_codes %></td>
          <td><%= guide.age_limitations %></td>
          <td><%= guide.state_mandate_apply? ? "Yes" : (guide.state_mandate_apply == false ? "No" : "")  %></td>
          <td><%= guide.major_medical_benefit? ? "Yes" : (guide.major_medical_benefit == false ? "No" : "")  %></td>
          <td><%= guide.rx_benefit? ? "Yes" : (guide.rx_benefit == false ? "No" : "")  %></td>
          <td><%= guide.pa_required? ? "Yes" : (guide.pa_required == false ? "No" : "")  %></td>
          <td><%= guide.pa_form_required? ? "Yes" : (guide.pa_form_required == false ? "No" : "")  %></td>
          <td><%= guide.pa_link %></td>
          <td><%= guide.pa_process %></td>
          <td><%= guide.coverage_notes %></td>
          <td><%= guide.accepted_billing_codes %></td>
          <td><%= guide.bo_modifier? ? "Yes" : (guide.bo_modifier == false ? "No" : "")  %></td>
          <td><%= guide.is_s9433? ? "Yes" : (guide.is_s9433 == false ? "No" : "")  %></td>
          <td><%= guide.coding_link %></td>
          <td><%= guide.nutricia_formulary_products %></td>
          <td><%= guide.open_or_closed_formulary %></td>
          <td><%= guide.formulary_exception_allowed? ? "Yes" : (guide.formulary_exception_allowed == false ? "No" : "")  %></td>
          <td><%= guide.formulary_form_required? ? "Yes" : (guide.formulary_form_required == false ? "No" : "")  %></td>
          <td><%= guide.formulary_link %></td>
          <td><%= guide.formulary_documentation_required? ? "Yes" : (guide.formulary_documentation_required == false ? "No" : "")  %></td>
          <td><%= guide.formulary_process %></td>
          <td><%= guide.reimbursement_fee_schedule? ? "Yes" : (guide.reimbursement_fee_schedule == false ? "No" : "")  %></td>
          <td><%= guide.reimbursement_link  %></td>
          <td><%= guide.product_reimbursement_rate  %></td>
          <td><%= guide.reimbursement_fees  %></td>
          <td><%= guide.other_notes %></td>
          <td><%= guide.relationship_to_wic  %></td>
          <td><%= guide.relationship_to_state_medicaid  %></td>
          <td><%= guide.relationship_to_other_programs  %></td>
          
      </tr>
      <% end %>
  </table>
<% end %>

app/views/guides/new.html.erb
<%= render 'form' %>

app/views/guides/show.html.erb
<div class="uk-grid" data-uk-grid-margin>
  <div class="uk-container uk-width-large-8-10 uk-width-small-10-10 uk-container-center">
   <%= render 'shared/header'%>
    <hr/>
  </div>
  </div>
  <div class="uk-grid" data-uk-grid-margin>
    <div class="uk-width-5-5 uk-container-center">
    	<%= render 'guides/show' %>
    </div>
  </div>
</div>