config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :guides
  
  resources :spreadsheets do
    collection do
      post :import
    end
  end
  
  resources :sessions
  
  get "admin" => "sessions#new", as: :admin
  

  

end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  before_action :is_admin
  
  def import
    state, file = params[:state], params[:file] 
    @error_messages = Guide.validate_document(file, state)
    @filename = file.original_filename
    if @error_messages.blank?
      @success = true
      Guide.import(file, state)
    end
    respond_to do |format|
      format.js
      format.html { redirect_to :back }
    end
  end
  
  
end

app/views/spreadsheets/_error.html.erb
<% if error.present? %>
	<div class="uk-alert uk-alert-danger" data-uk-alert>
		<%= error %>
	</div>
	<br/>
<% end %>

app/views/spreadsheets/_error_header.html.erb
<p class="uk-text-danger uk-text-center">
	<i class="material-icons uk-text-danger md-48">&#xE8B2;</i> 
	<br/>
	<u>
		Did not import file <i><%= filename %></i> because the spreadsheet has at least <%=pluralize error_messages_count, "error" %>:</u>
</p>

app/views/spreadsheets/_success.html.erb
<div class="uk-alert uk-alert-success" data-uk-alert>
    Successfully imported file <%= filename %>.
</div>
<p>
	<i class="material-icons">&#xE314;</i> <%= link_to "View Available Guides", guides_path %>
</p>
<hr>
  

app/views/spreadsheets/import.js.erb
<% if @error_messages.present? %>
    $('#upload-error-header').html("<%= j render 'spreadsheets/error_header', error_messages_count: @error_messages.count, filename: @filename %>")
    <% (0..@error_messages.count).to_a.each do |i| %>
    $('#error-<%= i %>').html("<%= j render 'spreadsheets/error', error: @error_messages[i] %>")
    <% end %>
<% elsif !@success.nil? %>
     $('#upload-error-header').hide()
     <% (0..15).to_a.each do |i| %>
     $('#error-<%= i %>').hide()
     <% end %>
     $('#upload-success').html("<%= j render 'spreadsheets/success', filename: @filename %>")
<% end %>

app/views/spreadsheets/index.html.erb
<div class="uk-grid" data-uk-grid-margin>
    <div class="uk-width-large-8-10 uk-width-small-10-10 uk-container-center">

     <%= render 'shared/header'%>

      <hr/>
     
      <div class="uk-width-medium-4-10 uk-container-center">

      	<p class="uk-text-center uk-clearfix">
	      	<%= link_to "Return to Homepage", root_path %>
	    	</p>

	      <div class="md-card uk-padding-remove">
	      	<div>
	      		<br/>
             <!--  <div class="md-card-toolbar-actions">
                  <i class="md-icon material-icons md-card-fullscreen-activate">&#xE5D0;</i>
                  <i class="md-icon material-icons">&#xE5D5;</i>
                  <div class="md-card-dropdown" data-uk-dropdown>
                      <i class="md-icon material-icons">&#xE5D4;</i>
                      <div class="uk-dropdown uk-dropdown-flip">
                          <ul class="uk-nav">
                              <li><a href="#">Action 1</a></li>
                              <li><a href="#">Action 2</a></li>
                          </ul>
                      </div>
                  </div>
              </div> -->
              <h3 class="heading_a uk-margin-top uk-text-center">
                Excel Spreadsheet Upload Form
                <span class="sub-heading">
                	Use the form below to upload a new excel spreadsheet.
                <span>
              </h3>
          </div>
          <hr/>
	        <div class="md-card-content uk-padding-top-remove">
	          <!-- search field -->
            <!-- beginning of form -->
					  <%= form_tag import_spreadsheets_path, id: "upload-form", multipart: true, :remote => true , class: "uk-width-medium-8-10 uk-container-center" do %>

							<div class="" id="upload-error-header"></div>

							<!-- add if statement -->
				  		<% (0..15).to_a.each do |i| %>
								<div id="error-<%= i %>"></div>
							<% end %>
							<div class="" id="upload-success"></div>
				  
					 
						  
						  <!-- select state  -->
					  	<p class="uk-text uk-text-primary">1. Select state.</p>
            	<%= select_tag :state, options_for_select(all_states, "California"), {class: "data-md-selectize", prompt: "Select State", id: "object-field"} %>
	            <br/>
	            <div class="uk-well">
	            	<p class="uk-text uk-text-primary">2. Click to upload MS Excel file.</p>
	            	<%= file_field_tag :file, id: "file-field", type: "file" %>
	          	</div>
		        </div>
		        
		        <hr class="uk-margin-remove"/>
		        <div class="md-card-content">
						  <!-- file submit button -->
						  <p class="uk-margin-small-top uk-margin-large-left uk-margin-large-right">
						  	<%= submit_tag "Import Spreadsheet", class: "md-btn md-btn-block md-btn-primary", disabled: false, id: "file-submit"%>
						  </p>

						<% end %>
					<!-- end of form -->

	        </div>
	      </div>

	    </div>
    </div>
  </div>